<?php  require_once("./header.php") ;?>
	<div class="wrap" id="story">
		<h1 class="center">Amazing takes time.</h1>
		<div class="p10 fl w5">
			<p>Mainely Burgers opened its windows in the summer of 2012, just as we - owners Jack Barber and Ben Berman - had finished our freshman year of college. The idea for the business began when we arrived at school in Boston earlier that year, fresh off graduation from Cape Elizabeth High School. Best friends since first grade, we were always connected by our love of food and in Boston we would meet up at different food trucks to catch up. We realized that Portland was missing out on this trend and that the city could benefit from the creativity, accessibility, and
			excitement of food trucks.</p>
			<p>Some people called us crazy when we started writing business plans for our own truck and there was a time when we agreed: Portland, such a great foodie city, didn't allow for food trucks. Still, determined to make our dream a reality, we decided on a new route and landed a spot at a beautiful beach on Maine's southern cost. For the summer, we took over food service for the beach with our brand new truck, serving up delicious, local food to hungry crowds.</p>
			<p>None of this could have happened without an incredible group of employees, mostly our remarkable younger brothers and close friends. We spent the summer as a team, learning, creating, and succeeding together, an experience that we will always cherish. This business has been an opportunity to learn—about food, working as a team, giving back to our community, being creative - and we can't wait to see where the road takes us. With an amazing first summer behind us, we have our eyes on the future, a future filled with big things for Mainely Burgers.</p>
			<p>We source everything as local and fresh as possible. Our goal is to create a delicious product that everyone can enjoy. We also love giving back to the community that has been so supportive in the development of this business.</p>
		</div>
		<div class="p10 fr w5">
			<p>We spent part of the summer lobbying city council members to allow for food trucks in the city and are happy to say that the law has officially changed. This creates major opportunities for expansion in the near future. We also cater parties and participate in concert series. With a goal to keep all customers happy and never let them walk away hungry, we've been excited to be invited to various public and private events around Southern Maine.</p>
			<p>It should come as no surprise that we love burgers, and Mainely Burgers is a reflection of our spin on the classic food. A unique menu catering to all ages and full of constantly changing specials has helped us find our niche. Most importantly, our products are fresh: we make all our own sauces and have our meat, produce, and buns delivered fresh daily. From the beginning, we focused on getting the most local products as possible. All natural, never-frozen burgers from Dole and Bailey in Massachusetts have set us apart from burger competitors. Our veggie burgers, all hand-made, and artisan buns, are made in Portland, most of our produce comes from Maine farms, and all cheeses are sourced from New England. We strive to make the highest quality product.</p>
			<p>The truck specialized in gourmet burgers, but the menu also includes veggie burgers, chicken sandwiches, hot dogs, and sides. We're truly proud of the menu, featuring burgers like "the Mainah" (with cheddar cheese, sauteed onions, sliced apple, bacon and our house-made maple mayo) and specials like "the Final Word" (with cheddar cheese, fresh avocado, pickled red onions, sauteed jalapenos, and house-made spicy Thai mayo). It has been our friendship that has driven the success of Mainely Burgers, but it is our love of food and creative menu that keeps our customers coming back.</p>
 		</div>
 		<div class="clear"></div>
	</div>
	</body>
</html>